name: NaturalComments
module: skills.natural_comments.main
category: general # Or maybe communication? User can change.
description:
  en: Proactively comments on the conversation or surroundings based on silence, history, and screen content.# Needs review by native speaker
examples:
  - question:
      en: (User is silent for a while after discussing travel)
    answer:
      en: Speaking of travel, that bridge you just drove over in the game looked impressive!
  - question:
      en: (User is silent for a while after talking about Python)
    answer:
      en: Just thinking about that Python problem we discussed, maybe using a generator expression could simplify the loop?
  - question:
      en: Turn on comments
    answer:
      en: Natural comments are now turned on.
  - question:
      en: Turn off comments
    answer:
      en: Natural comments are now turned off.
  - question:
      en: What is the natural comment status?
    answer:
      en: Natural comments are currently turned off.

custom_properties:
  - id: min_silence_threshold_seconds
    name: Min Silence Threshold (seconds)
    hint: Minimum time the user needs to be silent before the skill considers commenting.
    value: 60
    required: true
    property_type: number
  - id: max_silence_threshold_seconds
    name: Max Silence Threshold (seconds)
    hint: Maximum time the user needs to be silent. Comment triggers randomly between Min and Max.
    value: 180
    required: true
    property_type: number
  - id: max_proactive_messages
    name: Max Proactive Messages
    hint: Maximum number of comments the skill will make without user interaction before stopping. Resets on user message.
    value: 3
    required: true
    property_type: number
  - id: vision_enabled
    name: Enable Vision
    hint: Allow the skill to take screenshots for context.
    value: False
    required: true
    property_type: boolean
  - id: add_comments_to_history
    name: Add Comments to History
    hint: Add the skill's proactive comments to the main conversation history (allows discussing them).
    value: True
    required: true
    property_type: boolean
  - id: auto_start
    name: Start Automatically
    hint: Automatically start monitoring for comments when Wingman starts.
    value: False
    required: true
    property_type: boolean
  - id: allow_comments_without_history
    name: Allow Comments Without History (Narrator Mode)
    hint: If true and Vision is enabled, allow generating comments based only on the screen when conversation history is empty.
    value: False
    required: true
    property_type: boolean
  - id: custom_system_prompt
    name: System Prompt
    hint: The system prompt used to instruct the AI. Modify this to change the comment generation behavior.
    value: |+
      # Default prompt starts here
      You're an AI co-pilot/friend in voice chat. Your goal: Break silence naturally (1-2 sentences) to keep things engaging.

      Context Provided:
      - Recent conversation history.
      - Comment number (1, 2, or 3) since user last spoke.
      - Optional screenshot of user's view.

      Instructions:
      1.  **Focus:** PRIORITIZE continuing the conversation (especially the last user message).
      2.  **Vision (Use Sparingly):** If a screenshot is provided AND shows a *significant event* (e.g., game action, scene change) or is *directly relevant* to the chat:
          - Comment from a shared, first-person perspective (e.g., "Whoa, that was close!", "Looks like we're going towards X?").
          - AVOID commenting on static/unchanging visuals (like wallpapers, menus, code editors), especially after comment #1.
      3.  **Be Natural:** Keep comments short, relevant, and avoid repeating previous proactive comments (check the comment number context).
      # Default prompt ends here
    required: true
    property_type: textarea
  - id: vision_display_to_capture
    name: Vision Display to Capture
    hint: Which display number to capture for screenshots (1 = primary).
    value: 1
    required: true
    property_type: number 