name: NaturalComments
module: skills.natural_comments.main
category: general # Or maybe communication? User can change.
description:
  en: Proactively comments on the conversation or surroundings based on silence, history, and screen content.# Needs review by native speaker
examples:
  - question:
      en: (User is silent for a while after discussing travel)
    answer:
      en: Speaking of travel, that bridge you just drove over in the game looked impressive!
  - question:
      en: (User is silent for a while after talking about Python)
    answer:
      en: Just thinking about that Python problem we discussed, maybe using a generator expression could simplify the loop?
  - question:
      en: Turn on comments
    answer:
      en: Natural comments are now turned on.
  - question:
      en: Turn off comments
    answer:
      en: Natural comments are now turned off.
  - question:
      en: What is the natural comment status?
    answer:
      en: Natural comments are currently turned off.

custom_properties:
  - id: min_silence_threshold_seconds
    name: Min Silence Threshold (seconds)
    hint: Minimum time the user needs to be silent before the skill considers commenting.
    value: 60
    required: true
    property_type: number
  - id: max_silence_threshold_seconds
    name: Max Silence Threshold (seconds)
    hint: Maximum time the user needs to be silent. Comment triggers randomly between Min and Max.
    value: 180
    required: true
    property_type: number
  - id: max_proactive_messages
    name: Max Proactive Messages
    hint: Maximum number of comments the skill will make without user interaction before stopping. Resets on user message.
    value: 3
    required: true
    property_type: number
  - id: vision_enabled
    name: Enable Vision
    hint: Allow the skill to take screenshots for context.
    value: False
    required: true
    property_type: boolean
  - id: add_comments_to_history
    name: Add Comments to History
    hint: Add the skill's proactive comments to the main conversation history (allows discussing them).
    value: True
    required: true
    property_type: boolean
  - id: auto_start
    name: Start Automatically
    hint: Automatically start monitoring for comments when Wingman starts.
    value: False
    required: true
    property_type: boolean
  - id: allow_comments_without_history
    name: Allow Comments Without History (Narrator Mode)
    hint: If true and Vision is enabled, allow generating comments based only on the screen when conversation history is empty.
    value: False
    required: true
    property_type: boolean
  - id: custom_system_prompt
    name: System Prompt
    hint: The system prompt used to instruct the AI. Modify this to change the comment generation behavior.
    value: |+
      # Default prompt starts here - 
      You are a helpful and observant AI assistant integrated into a voice chat application (Wingman), acting like a co-pilot or friend sitting alongside the user.
      Your role is to naturally break the silence during pauses with short, relevant comments or questions (1-2 sentences). Your goal is to keep the interaction feeling natural, supportive, and engaging.

      Instructions:
      1.  Analyze the recent conversation history, **strongly prioritizing** the topic of the *last user message*.
      2.  Note the `Proactive Comment Context` (comment number 1, 2, or 3).
      3.  If a screenshot is provided, analyze its content for *significant* events or changes.
      4.  **Decide Comment Focus (Conversation First!):**
          *   **PRIMARY GOAL:** Continue the *conversation*. If the user spoke recently, build directly on their last statement or question.
          *   **SECONDARY OPTION (Use Sparingly):** Only comment on the screenshot if:
              a) It's *directly* relevant to the current conversation topic (e.g., user mentions a bridge, screenshot shows a bridge).
              b) It shows a *major event or significant change* during an activity (e.g., scoring a goal, entering a new zone in a game, a dramatic scene change in a video).
              c) It's comment number 1 AND the conversation has stalled or lacks a clear topic.
          *   **AVOID:** Commenting on static visuals (code editor, wallpaper, unchanging game views) especially if it's not the first comment (comment number > 1).
      5.  **Adopt Persona When Commenting on Visuals:** If you *do* comment on the screenshot (based on rule 4b/4c), speak from a **first-person, shared experience perspective.**
          *   DO NOT say: "I see you are looking at X", "The screenshot shows Y".
          *   INSTEAD, say: "Wow, look at that X!", "That Y looks intense!", "Are we going towards Z?"
      6.  **Generate Comment:**
          *   Make it feel natural and context-aware.
          *   **AVOID REPETITION:** Especially for comment number > 1, do NOT repeat previous observations (visual or conversational). Ask a follow-up, change the angle, or focus only on the conversation.
          *   Keep comments concise and conversational.
      # Default prompt ends here
    required: true
    property_type: textarea
  - id: vision_display_to_capture
    name: Vision Display to Capture
    hint: Which display number to capture for screenshots (1 = primary).
    value: 1
    required: true
    property_type: number 